<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="servo_length" value="0.045"/>
  <xacro:property name="servo_radius" value="0.015"/>
  <xacro:property name="arm_length" value="0.12"/>
  <xacro:property name="arm_width" value="0.002"/>
  <xacro:property name="arm_height" value="0.03"/>

  <xacro:property name="gs_length" value="0.1"/>
  <xacro:property name="gs_width" value="0.002"/>
  <xacro:property name="gs_height" value="0.025"/>

  <xacro:property name="arm2_length" value="0.11"/>
  <xacro:property name="arm2_width" value="0.002"/>
  <xacro:property name="arm2_height" value="0.03"/>

  <xacro:property name="base_length" value="0.225"/>
  <xacro:property name="base_width" value="0.15"/>
  <xacro:property name="base_height" value="0.055"/>
  <xacro:property name="PI" value="3.142593"/>
  
  <material name="white">
      <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
</material>

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
</material>

    <xacro:macro name="arm_default_transmission" params="joint_number" >
      <plugin>transmission_interface/SimpleTransmission</plugin>
      <transmission name="transmission_${joint_number}">
          <joint name="joint_${joint_number}" role="joint1">
              <mechanicalReduction>1.0</mechanicalReduction>
          </joint>
          <actuator name="servo_${joint_number}" role="actuator1"/>
      </transmission>
  </xacro:macro>

    <link name="baselink">
      <visual>
        <origin xyz="0.0 0.0 ${-base_height/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-base_height/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
      </collision>
      <xacro:box mass="1.0" length="${base_length}" width="${base_width}" height="${base_height}" 
            xyz="0.0 0.0 ${-base_height/2}" rpy="0.0 0.0 0.0"/>
    </link>
    <link name="world"/>
    <joint name="virtual_joint" type="fixed">
      <parent link="world"/>
      <child link="baselink"/>
      <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="link1">
      <visual name="">
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <xacro:cylinder mass="0.069" radius="${servo_radius}" height="${servo_length}"
            xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="joint_1" type="revolute">
      <parent link="baselink"/>
      <child link="link1"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${PI}" velocity="1.0" effort="1000.0"/>
      <origin xyz="0 0 ${servo_length}" rpy="0 0 0"/>
    </joint>
    
    <link name="link2">
      <visual name="">
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <xacro:cylinder mass="0.069" radius="${servo_radius}" height="${servo_length}"
            xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="joint_2" type="revolute">
      <parent link="link1"/>
      <child link="link2"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${PI}" velocity="1.0" effort="1000.0"/>
      <origin xyz="0 ${-servo_length/2} ${servo_radius}" rpy="${PI/2} 0 0"/>
    </joint>
    
    <link name="link3">
      <visual>
        <origin xyz="${-arm_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${arm_length} ${arm_height} ${arm_width}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${-arm_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${arm_length} ${arm_height} ${arm_width}"/>
        </geometry>
        <material name="grey"/>
      </collision>
      <xacro:box mass="0.05" length="${arm_length}" width="${arm_width}" height="${arm_height}" 
            xyz="${-arm_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    <joint name="dummy" type="fixed">
      <parent link="link2"/>
      <child link="link3"/>
      <origin xyz="${arm_length} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="link4">
      <visual name="">
        <origin xyz="0.0 0.0 ${servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <xacro:cylinder mass="0.069" radius="${servo_radius}" height="${servo_length}"
            xyz="0.0 0.0 ${servo_length/2}" rpy="0.0 0.0 0.0"/>
    </link>
    
    <joint name="joint_3" type="revolute">
      <parent link="link3"/>
      <child link="link4"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${PI}" velocity="1.0" effort="1000.0"/>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 0"/>
    </joint>


    <link name="link5">
      <visual>
        <origin xyz="0.0 ${arm_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${arm_height} ${arm_length} ${arm_width}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0.0 ${arm_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${arm_height} ${arm_length} ${arm_width}"/>
        </geometry>
        <material name="grey"/>
      </collision>
      <xacro:box mass="0.05" length="${arm_length}" width="${arm_width}" height="${arm_height}" 
            xyz="0.0 ${arm_length/2} 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    <joint name="dummy2" type="fixed">
      <parent link="link4"/>
      <child link="link5"/>
      <origin xyz="0.0 ${-arm_length} 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="link6">
      <visual name="">
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <xacro:cylinder mass="0.069" radius="${servo_radius}" height="${servo_length}"
            xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
    </link>
    
    <joint name="joint_4" type="revolute">
      <parent link="link5"/>
      <child link="link6"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${PI}" velocity="1.0" effort="1000.0"/>
      <origin xyz="0.0 0.0 0.02" rpy="${PI/2} 0 0"/>
    </joint>


    <!-- <link name="link7">
      <visual name="">
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${servo_radius}" length="${servo_length}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <xacro:cylinder mass="0.069" radius="${servo_radius}" height="${servo_length}"
            xyz="0.0 0.0 ${-servo_length/2}" rpy="0.0 0.0 0.0"/>
    </link> -->

    <!-- <joint name="joint_5" type="revolute">
      <parent link="link6"/>
      <child link="link7"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${PI}" velocity="1.0" effort="1000.0"/>
      <origin xyz="0 -0.035 0.01" rpy="${PI/2} 0 0"/>
    </joint> -->

    <link name="gripper_support">
      <visual>
        <origin xyz="${-gs_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${gs_length} ${gs_width} ${gs_height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${-gs_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${gs_length} ${gs_width} ${gs_height}"/>
        </geometry>
        <material name="grey"/>
      </collision>
      <xacro:box mass="0.05" length="${gs_length}" width="${gs_width}" height="${gs_height}" 
           xyz="${-gs_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    <joint name="dummy3" type="fixed">
      <parent link="link6"/>
      <child link="gripper_support"/>
      <origin xyz="${gs_length} 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
    </joint>

    <link name="gripper_right">
      <visual>
          <origin rpy="0 0 0" xyz="-0.06 0.0 0.0"/>
          <geometry>
              <mesh filename="package://buddy_arm_description/meshes/left_finger.STL" scale="0.001 0.001 0.001"/>
          </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="-0.06 0.0 0.0"/>
          <geometry>
              <mesh filename="package://buddy_arm_description/meshes/left_finger.STL" scale="0.001 0.001 0.001"/>  
          </geometry>
      </collision>
      <xacro:box mass="0.05" length="${gs_length}" width="${gs_width}" height="${gs_height}" 
            rpy="0 0 0" xyz="-0.06 0.0 0.0"/>
  </link>
  
  <joint name ="joint_5" type="revolute">
    <parent link="gripper_support"/>
    <child link = "gripper_right"/>
    <origin xyz="0.0 0.0 ${-gs_height/2}" rpy="${PI/2} 0.0 ${PI}"/>
    
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="${PI/4}" 
           effort="1000" velocity="10"/>
  </joint>

    <link name="gripper_left">
      <visual>
          <origin rpy="0 0 0" xyz="-0.06 ${-gs_height/2} 0.0"/>
          <geometry>
              <mesh filename="package://buddy_arm_description/meshes/right_finger.STL" scale="0.001 0.001 0.001"/>
          </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="-0.06 0.0 0.0"/>
          <geometry>
              <mesh filename="package://buddy_arm_description/meshes/right_finger.STL" scale="0.001 0.001 0.001"/>  
          </geometry>
      </collision>
      <xacro:box mass="0.05" length="${gs_length}" width="${gs_width}" height="${gs_height}" 
          rpy="0 0 0" xyz="-0.06 ${-gs_height/2} 0.0"/>
  </link>

  <joint name ="joint_6" type="revolute">
    <parent link="gripper_support"/>
    <child link = "gripper_left"/>
    <origin xyz="0.0 0.0 ${gs_height/2}" rpy="${PI/2} 0.0 ${PI}"/>
    
    <axis xyz="0 0 1"/>
    <limit lower="${-PI/4}" upper="0.0" 
           effort="1000" velocity="10"/>
           <mimic joint="joint_5" multiplier="-1"/>
  </joint>

  <!-- my fix for moveit -->
  <joint name="joint_6_mimic" type="fixed">
    <parent link="world" />
    <child link="random" />
  </joint>
  <link name="random"/> 

    

    
    <xacro:arm_default_transmission joint_number="1"></xacro:arm_default_transmission>
    <xacro:arm_default_transmission joint_number="2"></xacro:arm_default_transmission>
    <xacro:arm_default_transmission joint_number="3"></xacro:arm_default_transmission>
    <xacro:arm_default_transmission joint_number="4"></xacro:arm_default_transmission>
    <xacro:arm_default_transmission joint_number="5"></xacro:arm_default_transmission>
    <xacro:arm_default_transmission joint_number="6"></xacro:arm_default_transmission>

</robot>